name: Deployment

on:
  push:
    tags:
    - '*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Initialise ENV file
        run: cp .env.example .env
      - name: Add Pirsch analytics site code to ENV file
        run: sed -i 's/PIRSCH_ANALYTICS_SITE_CODE=/PIRSCH_ANALYTICS_SITE_CODE=${{ secrets.PIRSCH_ANALYTICS_SITE_CODE }}/' .env
      - name: Add Last.fm API key to ENV file
        run: sed -i 's/LASTFM_API_KEY=/LASTFM_API_KEY=${{ secrets.LASTFM_API_KEY }}/' .env
      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.25.0
      - name: Install Lume
        run: deno run -A https://deno.land/x/lume/install.ts
      - name: Build site
        run: ./bin/build
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "murty-website"
          entrypoint: "./src/server.ts"