name: Deployment

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Setup checkout
      uses: actions/checkout@v1
    - name: Run commands on the server
      uses: brendanmurty/github-action-ssh@release
      with:
        command: |
          export DENO_INSTALL="/root/.deno"
          export PATH="$DENO_INSTALL/bin:$PATH"
          cd ${{ secrets.REMOTE_DIRECTORY }}
          git pull origin main --quiet
          ./bin/build
          rm -r /var/www/html/*
          sudo cp -r public/* /var/www/html
          cp bin/config/.htaccess /var/www/html
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}