name: Run tests
on:
  workflow_dispatch: # Allow manual runs
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Deno
        uses: "denoland/setup-deno@v1"
        with:
          deno-version: ^1.4
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          deno task setup
          apt-get -y install exiftool
          sed -i -e "s/GOOGLE_ANALYTICS_SITE_CODE=/GOOGLE_ANALYTICS_SITE_CODE=${{ secrets.GOOGLE_ANALYTICS_SITE_CODE }}/g" .env
          cat .env
      - name: Run tests
        run: deno task test
