name: Run tests
on:
  workflow_dispatch: # Allow manual runs
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: linux
    steps:
      - name: Setup Deno
        uses: "denoland/setup-deno@v1"
        with:
          deno-version: ^1.4
      - name: Run tests
        run: deno task test
