#
#
# GitHub Actions Workflow: Test
#   - Includes the build and test processes
#
#

name: Test
run-name: Test ${{ github.run_number }} from ${{ github.actor }} on the ${{ github.ref_name }} ${{ github.ref_type }}

on:
  # Manual run via GitHub Repo > Actions > Test > Run workflow
  workflow_dispatch:
  # Automatically run on PRs that are targetting 'main'
  pull_request:
    branches:
      - main
    paths:
      - .github/**
      - app/**
      - deno.json
      - deno.lock

defaults:
  run:
    shell: bash

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    environment:
      name: ci-build
      deployment: false
    env: ${{ secrets }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          ref: 'main'
          fetch-depth: 1
          show-progress: false
      - name: Deno Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - name: Run Tests
        run: ./task test
