name: Run tests
on:
  workflow_dispatch: # Allow manual runs
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Deno
        uses: "denoland/setup-deno@v1"
        with:
          deno-version: ^1.45
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          deno task setup
          sudo apt-get -y install exiftool
      - name: Run tests
        run: deno task test
